### ISSUE TITLE
]用户于手机客户端退出登陆, 响应码:1101, 描述信息未检测到登录

### ISSUE THREAD

**Issue by qsgy** [leantli/wc_robot#10]
[INFO]本次登陆状态检查码为201, 信息为已扫码，待手机上确认
 [INFO]本次登陆状态检查码为200, 信息为扫码登陆成功
 [INFO]Sync得到响应 retCode=1101, selector=0
 [INFO]用户于手机客户端退出登陆, 响应码:1101, 描述信息未检测到登录

小号登不了。大号可以登

**Comment by leantli** [comment]
您好，邮件已收到，谢谢

**Comment by leantli** [comment]
哈喽，现在微信在网页版/UOS 端限制登录条件比较多，可以看看小号是不是没有实名认证，没有实名认证的话可以参考下这篇 [微信如何实名认证](https://jingyan.baidu.com/article/5d6edee2d3acc1d8ebdeec65.html)
