### ISSUE TITLE
Operation error

### ISSUE THREAD

**Issue by phpoh** [leantli/wc_robot#11]
go: downloading github.com/jasonlvhit/gocron v0.0.1
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
tasks\tasks.go:13:2: github.com/jasonlvhit/gocron@v0.0.1: Get "https://proxy.golang.org/github.com/jasonlvhit/gocron/@v/v0.0.1.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
robot\caller.go:21:2: github.com/skip2/go-qrcode@v0.0.0-20200617195104-da1b6568686e: Get "https://proxy.golang.org/github.com/skip2/go-qrcode/@v/v0.0.0-20200617195104-da1b6568686e.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
common\config.go:9:2: gopkg.in/yaml.v3@v3.0.1: Get "https://proxy.golang.org/gopkg.in/yaml.v3/@v/v3.0.1.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by leantli** [comment]
这个应该是环境问题，两个方法：
1. 科学上网，因为国内访问 go 默认的下载源容易超时甚至连不上，你可以通过 `go env` 指令查看一下自己 go 环境的配置
2. 暂时没有科学上网手段的话给 go proxy 配个国内的的代理，详细操作见 [链接](https://blog.csdn.net/weixin_42852778/article/details/125720599)
