### ISSUE TITLE
试了下不行呢？麻烦给看看

### ISSUE THREAD

**Issue by wxq3d** [leantli/wc_robot#12]
![微信图片编辑_20230222191317](https://user-images.githubusercontent.com/4547561/220604229-a81bd6a9-603c-453f-b4d7-454d5cce567e.jpg)

**Comment by leantli** [comment]
您好，邮件已收到，谢谢

**Comment by leantli** [comment]
不搞这个项目了应该，这几个月因为 chatGPT 太火了，太多人玩微信机器人接入 gpt 了，导致 微信 的检测严格了一些，基于 openwechat 这种 模拟客户端通信 的方式最容易被微信检测到，你可以搜一下 微信 hook 方式的其他机器人项目，hook 方式的比较难被检测查杀
当然我这个项目确实用起来比较方便，如果一定要继续用的话，记得开小号，你这个登陆马上退出的情况一般是没有完成小号的实名认证？可以参考下这篇 [微信如何实名认证](https://jingyan.baidu.com/article/5d6edee2d3acc1d8ebdeec65.html)

**Comment by wxq3d** [comment]
感谢！
