### ISSUE TITLE
机器人功能阉割太多了

### ISSUE THREAD

**Issue by Wyatex** [leantli/wc_robot#5]
虽说是根据原版openwechat来改，但是这代码也太精简了吧XD
有些功能，比如想拿到群聊里是谁发的消息，我以为getSender能用，结果报错一看才发现都没写

**Comment by leantli** [comment]
您好，邮件已收到，谢谢

**Comment by leantli** [comment]
@Wyatex 对的，因为 openwechat 算是一个脚手架，提供的能力会尽可能的完善，我这边考虑实现的是一个上手可用的工具，因此实现的时候仅仅根据要实现的能力，只取了 openwechat 必需的部分，老哥如果有什么具体的需求可以提一下，我也可以补充一下 🤩

**Comment by Wyatex** [comment]
算了有空还是我自己再造一个吧😵‍💫

**Comment by leantli** [comment]
好吧，还想再丰富一下功能，因为我搞的功能都只是基于我自身需求搞的，感觉东西还是有点少🤕

**Comment by Wyatex** [comment]
主是如果想自己加内容的话会发现缺太多轮子了，而且不好加回去😭

**Comment by leantli** [comment]
好吧，老哥噶油，我看看我这后面也可以搞个分支就完全基于 openwechat，方便二次开发
